# Generated by Django 6.0.6 on 2026-07-05 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, verbose_name="Warehouse'")),
                ('location', models.CharField(max_length=30, verbose_name="Warehouse's location")),
                ('capacity', models.IntegerField(verbose_name="Warehouse's capacity")),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name="Product's name")),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('description', models.CharField(max_length=50, verbose_name='Description')),
                ('status', models.CharField(choices=[('avalaible', 'Avalaible'), ('perime', 'Perime'), ('reserved', 'Reserved')], default='avalaible', verbose_name='Status')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecostock.warehouse')),
            ],
        ),
    ]
